name: linting


on:
  push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.7

      - name: Install dependencies
        run: cd lib && pip install -U pip && pip install -e .[dev]

      - name: Run flake8
        run: python -m flake8 lib/
